frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**'

backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**'

ci/cd:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

docs:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

config:
  - changed-files:
    - any-glob-to-any-file:
      - 'render.yaml'
      - 'vercel.json'
      - 'frontend/craco.config.js'
      - 'frontend/tailwind.config.js'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - 'backend/requirements.txt'
