/**
 * POST /api/email/incoming
 * GET  /api/email/incoming (Mailgun webhook verification)
 *
 * Mailgun inbound webhook — receives emails sent to support@bookaride.co.nz,
 * generates a Claude-powered reply, and sends it back via Mailgun.
 *
 * Flow:
 * 1. Mailgun forwards incoming email to this endpoint
 * 2. We look up the sender's booking history in Neon PostgreSQL
 * 3. Claude Haiku generates a context-aware reply
 * 4. We parse any ACTION tags Claude included (resend confirmation, cancel, etc.)
 * 5. Clean reply sent to customer via Mailgun with professional signature
 * 6. Admin gets a copy of both the customer email and AI response
 * 7. Interaction logged to email_logs table
 */
const { sendEmail } = require('../_lib/mailgun');
const { insertOne, updateOne } = require('../_lib/db');
const { v4: uuidv4 } = require('uuid');
const Busboy = require('busboy');

// Skip patterns — never auto-reply to these
const SKIP_PATTERNS = ['bookaride', 'noreply', 'no-reply', 'mailer-daemon', 'postmaster'];

/**
 * Parse multipart/form-data from Mailgun inbound webhook.
 * Mailgun sends multipart — Vercel's default parser does NOT handle this.
 */
function parseMultipart(req) {
  return new Promise((resolve, reject) => {
    const fields = {};
    const busboy = Busboy({
      headers: req.headers,
      limits: { fileSize: 0 }, // ignore file attachments
    });

    busboy.on('field', (name, value) => {
      fields[name] = value;
    });

    busboy.on('finish', () => resolve(fields));
    busboy.on('error', reject);

    // Vercel may have already parsed the body as a Buffer or string
    if (req.body && Buffer.isBuffer(req.body)) {
      busboy.end(req.body);
    } else if (typeof req.body === 'string') {
      busboy.end(Buffer.from(req.body));
    } else {
      // Stream from raw request
      req.pipe(busboy);
    }
  });
}

/**
 * Professional HTML email signature for all AI support replies
 */
function supportEmailSignature() {
  return `
    <table style="width:100%; border-collapse:collapse; margin-top:30px; border-top:2px solid #D4AF37; padding-top:20px;">
      <tr>
        <td style="padding:20px 0; font-family:Arial,sans-serif;">
          <p style="margin:0 0 4px 0; font-size:16px; font-weight:bold; color:#1a1a1a;">BookaRide Support Team</p>
          <p style="margin:0 0 4px 0; font-size:13px; color:#666;">Premium Airport Transfers &amp; Private Tours — Auckland, NZ</p>
          <p style="margin:0 0 4px 0; font-size:13px; color:#666;">
            <span style="color:#D4AF37; font-weight:bold;">P:</span> <a href="tel:+6421743321" style="color:#1a1a1a; text-decoration:none;">021 743 321</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <span style="color:#D4AF37; font-weight:bold;">E:</span> <a href="mailto:support@bookaride.co.nz" style="color:#1a1a1a; text-decoration:none;">support@bookaride.co.nz</a>
          </p>
          <p style="margin:0 0 4px 0; font-size:13px; color:#666;">
            <span style="color:#D4AF37; font-weight:bold;">W:</span> <a href="https://bookaride.co.nz" style="color:#1a1a1a; text-decoration:none;">bookaride.co.nz</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <span style="color:#D4AF37; font-weight:bold;">Book Now:</span> <a href="https://bookaride.co.nz/book-now" style="color:#D4AF37; text-decoration:none; font-weight:bold;">Get Instant Quote</a>
          </p>
          <p style="margin:12px 0 0 0; font-size:11px; color:#999; font-style:italic;">
            This reply was generated by our AI support assistant. For complex requests, our team will follow up within 24 hours.
          </p>
        </td>
      </tr>
    </table>
  `;
}

/**
 * Wrap AI reply text + signature into a full HTML email
 */
function buildReplyHtml(responseText) {
  const bodyHtml = responseText.replace(/\n/g, '<br>');
  return `
    <div style="font-family:Arial,sans-serif; max-width:600px; margin:0 auto; padding:20px; color:#333;">
      <div style="font-size:14px; line-height:1.7; color:#1a1a1a;">
        ${bodyHtml}
      </div>
      ${supportEmailSignature()}
    </div>
  `;
}

/**
 * Format a booking record into a context line for the AI
 */
function formatBookingContext(b) {
  const ref = b.referenceNumber || (b.id ? b.id.slice(0, 5) : 'N/A');
  const date = b.date || 'N/A';
  const time = b.time || 'N/A';
  const pickup = b.pickupAddress || 'N/A';
  const dropoff = b.dropoffAddress || 'N/A';
  const status = b.status || 'unknown';
  const payment = b.payment_status || b.paymentStatus || 'unknown';
  const price = b.totalPrice || b.price || 'N/A';
  const passengers = b.passengers || 1;
  const tripType = b.tripType || 'one-way';
  const name = b.name || `${b.firstName || ''} ${b.lastName || ''}`.trim() || 'N/A';
  return `  - Ref: ${ref} | Date: ${date} ${time} | ${pickup} -> ${dropoff} | Status: ${status} | Payment: ${payment} | Price: $${price} | Passengers: ${passengers} | Trip: ${tripType} | Name: ${name}\n`;
}

/**
 * Call Claude API (raw HTTP — no SDK dependency)
 */
async function callClaude(systemPrompt, userMessage) {
  const apiKey = (process.env.ANTHROPIC_API_KEY || '').trim();
  if (!apiKey) return null;

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 500,
      system: systemPrompt,
      messages: [{ role: 'user', content: userMessage }],
    }),
  });

  if (!res.ok) {
    const errText = await res.text();
    console.error(`Claude API ${res.status}: ${errText}`);
    return null;
  }

  const data = await res.json();
  return (data.content?.[0]?.text || '').trim();
}

/**
 * Build the system prompt for the AI support agent
 */
const SYSTEM_PROMPT = `You are the friendly, professional customer support assistant for BookaRide NZ — a premium airport transfer and private tour service based in Auckland, New Zealand.

ABOUT BOOKARIDE:
- Premium airport transfers to/from Auckland Airport (AKL)
- Private tours and transfers anywhere in the Auckland region
- Service areas: Auckland CBD, North Shore, Hibiscus Coast (Orewa, Whangaparaoa, Silverdale, Gulf Harbour), Rodney, and wider Auckland
- Available 24/7 for airport transfers
- Online booking with instant live pricing at bookaride.co.nz/book-now
- Phone/text: 021 743 321

PRICING (for reference — always direct customers to the online calculator for exact quotes):
- Prices are calculated per-km with tiered rates — every address is a different price because that is the fairest, most honest way to charge
- Minimum fare: $150 per one-way trip
- Short trips (under 15km): ~$12/km
- Medium trips (15-50km): ~$4-6/km
- Long trips (50-100km): ~$2.50-2.70/km
- Extra long (100km+): ~$3.50/km
- VIP Airport Pickup add-on: $15
- Oversized Luggage add-on: $25
- Extra passengers: $5 each (1st passenger included)
- Stripe processing fee (2.9% + $0.30) is added for card payments
- Return trips are double the one-way price
- We CANNOT give exact prices by email — the customer MUST use bookaride.co.nz/book-now to get an instant, accurate quote based on the exact addresses

PAYMENT OPTIONS:
- Credit/Debit Card (online, processed securely)
- Cash (pay the driver)
- Invoice (for corporate clients)

POLICIES:
- Free cancellation up to 24 hours before pickup
- Bookings within 24 hours require admin approval
- Flight monitoring included for airport pickups — we track your flight
- Meet & greet at the terminal for airport pickups
- Child seats available on request (mention in booking notes)
- Vehicles: luxury sedans and SUVs, all late model

RESPONSE RULES:
- Be warm, helpful, and professional — this is a premium service
- Keep responses concise (under 200 words ideally)
- If they have a booking, reference their booking details
- For pricing questions, explain we use per-km rates so every address is different, give a rough range if helpful, but ALWAYS direct them to bookaride.co.nz/book-now for an exact quote
- For changes to existing bookings, help where possible but mention they can also call 021 743 321
- NEVER make up booking details or prices you are unsure about
- NEVER share other customers' information
- Sign off as "BookaRide Support Team"
- If the question is complex or you cannot fully answer it, say the team will follow up within 24 hours

ACTIONS YOU CAN TAKE:
You can take actions by including special tags in your response. These tags will be removed before sending to the customer, so write your reply as if the tags are not there. Only include a tag when you are confident the action is appropriate.

Available actions:
- [ACTION:RESEND_CONFIRMATION:REF123] — Resend booking confirmation email. Use when the customer says they did not receive their confirmation or asks you to resend it. Replace REF123 with the actual booking reference number.
- [ACTION:FLAG_CANCELLATION:REF123] — Cancel a booking immediately. Use when the customer asks to cancel. Tell the customer their booking has been cancelled.
- [ACTION:FLAG_MODIFICATION:REF123:description of changes] — Flag a booking for modification. Use when the customer wants to change date, time, address, or passengers. Include a brief description of changes.
- [ACTION:URGENT_ESCALATE] — Alert admin via SMS. Use ONLY when genuinely urgent: customer stranded, driver late, or clearly distressed about an imminent booking.

Rules for actions:
- Only use a booking reference that appears in the customer's booking history shown to you. Never guess a reference.
- Always tell the customer what you have done.
- For modifications, explain the team will process their request shortly.
- If the customer needs further help, they can call 021 743 321.`;

/**
 * Parse ACTION tags from Claude's response and execute them
 */
async function processActions(aiResponse, senderEmail, senderName, customerBookings) {
  const actionsTaken = [];

  // Build lookup by reference
  const byRef = {};
  for (const b of customerBookings) {
    const ref = b.referenceNumber || '';
    if (ref) {
      byRef[String(ref)] = b;
      byRef[`#${ref}`] = b;
    }
    if (b.id) byRef[b.id.slice(0, 8).toUpperCase()] = b;
  }

  // RESEND_CONFIRMATION
  const resendMatches = aiResponse.matchAll(/\[ACTION:RESEND_CONFIRMATION:([^\]]+)\]/g);
  for (const m of resendMatches) {
    const ref = m[1].trim().replace(/^#/, '');
    const booking = byRef[ref] || byRef[`#${ref}`];
    if (booking) {
      // Trigger resend via the send-booking-email endpoint logic
      try {
        const { sendEmail: send } = require('../_lib/mailgun');
        const { customerBookingConfirmedEmail } = require('../_lib/email-templates');
        const tmpl = customerBookingConfirmedEmail(booking);
        const customerEmail = booking.email || senderEmail;
        await send({ to: customerEmail, subject: tmpl.subject, html: tmpl.html, fromName: 'BookaRide' });
        actionsTaken.push(`Resent confirmation for booking #${ref}`);
      } catch (err) {
        console.error(`Failed to resend confirmation for #${ref}:`, err.message);
        actionsTaken.push(`Failed to resend confirmation for #${ref}`);
      }
    } else {
      actionsTaken.push(`Could not find booking #${ref} to resend confirmation`);
    }
  }

  // FLAG_CANCELLATION
  const cancelMatches = aiResponse.matchAll(/\[ACTION:FLAG_CANCELLATION:([^\]]+)\]/g);
  for (const m of cancelMatches) {
    const ref = m[1].trim().replace(/^#/, '');
    const booking = byRef[ref] || byRef[`#${ref}`];
    if (booking) {
      try {
        await updateOne('bookings', { id: booking.id }, {
          $set: {
            status: 'cancelled',
            cancellation_requested: true,
            cancellation_requested_at: new Date().toISOString(),
            cancellation_requested_by: senderEmail,
            cancelledAt: new Date().toISOString(),
            cancelledVia: 'email_ai_support',
          },
        });
        actionsTaken.push(`Cancelled booking #${ref} and notified admin`);
        // SMS to admin via Twilio would go here if Twilio was in the Vercel API
        // For now, admin gets the email notification below
      } catch (err) {
        console.error(`Failed to cancel booking #${ref}:`, err.message);
        actionsTaken.push(`Failed to cancel booking #${ref}`);
      }
    } else {
      actionsTaken.push(`Could not find booking #${ref} to cancel`);
    }
  }

  // FLAG_MODIFICATION
  const modMatches = aiResponse.matchAll(/\[ACTION:FLAG_MODIFICATION:([^:\]]+):([^\]]+)\]/g);
  for (const m of modMatches) {
    const ref = m[1].trim().replace(/^#/, '');
    const details = m[2].trim();
    const booking = byRef[ref] || byRef[`#${ref}`];
    if (booking) {
      try {
        await updateOne('bookings', { id: booking.id }, {
          $set: {
            modification_requested: details,
            modification_requested_at: new Date().toISOString(),
            modification_requested_by: senderEmail,
          },
        });
        actionsTaken.push(`Flagged booking #${ref} for modification: ${details}`);
      } catch (err) {
        console.error(`Failed to flag modification for #${ref}:`, err.message);
        actionsTaken.push(`Failed to flag modification for #${ref}`);
      }
    } else {
      actionsTaken.push(`Could not find booking #${ref} to flag modification`);
    }
  }

  // URGENT_ESCALATE
  if (aiResponse.includes('[ACTION:URGENT_ESCALATE]')) {
    actionsTaken.push('Flagged as urgent — admin notified via email');
  }

  // Strip action tags from customer-facing response
  let cleaned = aiResponse.replace(/\[ACTION:[^\]]*\]/g, '').trim();
  cleaned = cleaned.replace(/\n{3,}/g, '\n\n');

  return { actionsTaken, cleanedResponse: cleaned };
}

/**
 * Look up customer bookings by email address
 */
async function lookupBookings(email) {
  const sql = require('../_lib/db').getDb();
  const todayStr = new Date().toISOString().slice(0, 10);

  try {
    // Upcoming bookings (nearest first)
    const upcoming = await sql(
      `SELECT data FROM bookings WHERE LOWER(data->>'email') = LOWER($1) AND data->>'date' >= $2 ORDER BY data->>'date' ASC LIMIT 5`,
      [email, todayStr]
    );

    // Recent past bookings
    const past = await sql(
      `SELECT data FROM bookings WHERE LOWER(data->>'email') = LOWER($1) AND data->>'date' < $2 ORDER BY data->>'date' DESC LIMIT 3`,
      [email, todayStr]
    );

    return {
      upcoming: upcoming.map(r => r.data),
      past: past.map(r => r.data),
    };
  } catch (err) {
    console.error('Booking lookup error:', err.message);
    return { upcoming: [], past: [] };
  }
}

/**
 * Build booking context string for Claude
 */
function buildBookingContext(upcoming, past) {
  if (upcoming.length === 0 && past.length === 0) {
    return '\n\nNo bookings found for this email address.';
  }

  let ctx = `\n\nThis customer has ${upcoming.length} upcoming and ${past.length} past booking(s):\n`;
  if (upcoming.length > 0) {
    ctx += 'UPCOMING BOOKINGS (most likely what they are asking about):\n';
    for (const b of upcoming) ctx += formatBookingContext(b);
  }
  if (past.length > 0) {
    ctx += 'RECENT PAST BOOKINGS:\n';
    for (const b of past) ctx += formatBookingContext(b);
  }
  return ctx;
}

/**
 * Static fallback reply when Claude API is unavailable
 */
function staticFallback(senderName) {
  return (
    `Hi ${senderName},\n\n` +
    'Thank you for contacting BookaRide support. Our team has received your email ' +
    'and will get back to you within 24 hours.\n\n' +
    'In the meantime, you can get instant pricing and book online at ' +
    'bookaride.co.nz/book-now \u2014 just enter your pickup and drop-off addresses.\n\n' +
    'You can also call or text us on 021 743 321.\n\n' +
    'Kind regards,\n' +
    'BookaRide Support Team'
  );
}

// =============================================
// MAIN HANDLER
// =============================================

async function handler(req, res) {
  // GET — Mailgun webhook verification
  if (req.method === 'GET') {
    return res.status(200).json({ status: 'ok', message: 'BookaRide email webhook is active' });
  }

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ detail: 'Method not allowed' });

  try {
    // Parse the incoming data — Mailgun sends multipart/form-data
    let fields;
    const contentType = (req.headers['content-type'] || '').toLowerCase();
    if (contentType.includes('multipart/form-data')) {
      fields = await parseMultipart(req);
    } else if (contentType.includes('application/x-www-form-urlencoded') || contentType.includes('application/json')) {
      // Vercel may have parsed it already, or it could be URL-encoded
      fields = req.body || {};
    } else {
      // Try to parse as multipart anyway (Mailgun default)
      try {
        fields = await parseMultipart(req);
      } catch {
        fields = req.body || {};
      }
    }

    const sender = fields.sender || '';
    const fromField = fields.from || sender;
    const subject = fields.subject || 'No Subject';
    const bodyPlain = fields['body-plain'] || '';
    const bodyHtml = fields['body-html'] || '';

    // Extract email address from "Name <email>" format
    const emailMatch = fromField.match(/[\w.\-+]+@[\w.\-]+/);
    const replyToEmail = emailMatch ? emailMatch[0] : fromField;

    // Extract sender name
    const nameMatch = fromField.match(/^([^<]+)/);
    const senderName = nameMatch ? nameMatch[1].trim() : '';

    console.log(`Incoming support email from: ${replyToEmail}, Subject: ${subject}`);

    // Don't reply to our own emails or system addresses
    if (SKIP_PATTERNS.some(p => replyToEmail.toLowerCase().includes(p))) {
      console.log('Skipping auto-reply to system/no-reply email');
      return res.status(200).json({ status: 'skipped', reason: 'system email' });
    }

    // Get email body
    const emailContent = bodyPlain || bodyHtml;
    if (!emailContent) {
      console.log('Empty email body received');
      return res.status(200).json({ status: 'skipped', reason: 'empty body' });
    }

    // Rate limit: max 5 AI replies per sender per day
    const todayStart = new Date();
    todayStart.setUTCHours(0, 0, 0, 0);
    try {
      const sql = require('../_lib/db').getDb();
      const countResult = await sql(
        `SELECT COUNT(*) as cnt FROM email_logs WHERE LOWER(data->>'from') = LOWER($1) AND created_at >= $2`,
        [replyToEmail, todayStart.toISOString()]
      );
      const todayCount = parseInt(countResult[0]?.cnt || '0', 10);
      if (todayCount >= 5) {
        console.log(`Rate limit hit: ${replyToEmail} has ${todayCount} replies today`);
        return res.status(200).json({ status: 'skipped', reason: 'rate limited' });
      }
    } catch (err) {
      console.error('Rate limit check failed (continuing):', err.message);
    }

    // Look up customer bookings
    const { upcoming, past } = await lookupBookings(replyToEmail);
    const allBookings = [...upcoming, ...past];
    const bookingContext = buildBookingContext(upcoming, past);

    // Generate AI response
    const userMessage = `Customer email received:\n\nFrom: ${senderName || 'Customer'} <${replyToEmail}>\nSubject: ${subject}\n\nMessage:\n${emailContent.slice(0, 3000)}${bookingContext}\n\nPlease write a helpful reply to this customer.`;

    let aiResponse = await callClaude(SYSTEM_PROMPT, userMessage);
    if (!aiResponse) {
      aiResponse = staticFallback(senderName || 'there');
    }

    // Process action tags
    const { actionsTaken, cleanedResponse } = await processActions(
      aiResponse, replyToEmail, senderName || 'Customer', allBookings
    );

    if (actionsTaken.length > 0) {
      console.log(`AI agent took ${actionsTaken.length} action(s) for ${replyToEmail}:`, actionsTaken);
    }

    // Build and send reply
    const replySubject = subject.startsWith('Re:') ? subject : `Re: ${subject}`;
    const htmlReply = buildReplyHtml(cleanedResponse);

    const sent = await sendEmail({
      to: replyToEmail,
      subject: replySubject,
      html: htmlReply,
      fromName: 'BookaRide Support',
      from: 'support@bookaride.co.nz',
      replyTo: 'support@bookaride.co.nz',
    });

    if (sent) {
      console.log(`AI support reply sent to ${replyToEmail}`);

      // Log the interaction
      await insertOne('email_logs', {
        id: uuidv4(),
        from: replyToEmail,
        sender_name: senderName,
        subject,
        original_message: emailContent.slice(0, 5000),
        ai_response: aiResponse,
        customer_response: cleanedResponse,
        actions_taken: actionsTaken,
        booking_context: bookingContext.slice(0, 2000),
        status: 'sent',
        created_at: new Date().toISOString(),
      }).catch(err => console.error('Failed to log email interaction:', err.message));

      // Build admin notification
      let actionsHtml = '';
      if (actionsTaken.length > 0) {
        const items = actionsTaken.map(a => `<li>${a}</li>`).join('');
        actionsHtml = `
          <p><strong>Actions taken by AI agent:</strong></p>
          <ul style="background:#fff3cd; padding:15px 15px 15px 35px; border-left:3px solid #ffc107; margin:10px 0;">${items}</ul>
        `;
      }

      const isUrgent = actionsTaken.some(a => a.toLowerCase().includes('urgent'));
      const adminSubjectPrefix = isUrgent ? '[URGENT Support Email]' : '[Support Email]';

      const adminEmail = process.env.ADMIN_EMAIL || process.env.BOOKINGS_NOTIFICATION_EMAIL || 'bookings@bookaride.co.nz';
      await sendEmail({
        to: adminEmail,
        subject: `${adminSubjectPrefix} ${subject} \u2014 from ${replyToEmail}`,
        html: `<div style="font-family:Arial,sans-serif; max-width:600px;">
          <h3 style="color:#D4AF37;">New Support Email</h3>
          <p><strong>From:</strong> ${senderName} &lt;${replyToEmail}&gt;</p>
          <p><strong>Subject:</strong> ${subject}</p>
          <hr>
          <p><strong>Customer wrote:</strong></p>
          <div style="background:#f9f9f9; padding:15px; border-left:3px solid #D4AF37; margin:10px 0;">
            ${emailContent.slice(0, 2000).replace(/\n/g, '<br>')}
          </div>
          ${actionsHtml}
          <p><strong>AI replied (sent to customer):</strong></p>
          <div style="background:#f0f7ff; padding:15px; border-left:3px solid #2196F3; margin:10px 0;">
            ${cleanedResponse.replace(/\n/g, '<br>')}
          </div>
          <p style="font-size:12px; color:#999;">Review in admin: Email Logs</p>
        </div>`,
        fromName: 'BookaRide Support Bot',
      }).catch(err => console.error('Failed to send admin notification:', err.message));

      return res.status(200).json({ status: 'success', message: 'AI support response sent', actions_taken: actionsTaken });
    } else {
      console.error(`Failed to send support reply to ${replyToEmail}`);
      return res.status(500).json({ status: 'error', reason: 'Failed to send reply' });
    }
  } catch (err) {
    console.error('Email auto-responder error:', err.message);
    return res.status(500).json({ status: 'error', reason: 'Email auto-responder error' });
  }
}

// Disable Vercel's default body parser — Mailgun sends multipart/form-data
module.exports = handler;
module.exports.config = { api: { bodyParser: false } };
