/**
 * POST /api/contact
 * Contact form submission — sends email to admin AND an AI-powered
 * auto-reply to the customer via the same Claude support agent.
 */
const { sendEmail } = require('./_lib/mailgun');
const { insertOne } = require('./_lib/db');
const { v4: uuidv4 } = require('uuid');

/**
 * Professional HTML email signature (matches support@bookaride.co.nz replies)
 */
function supportEmailSignature() {
  return `
    <table style="width:100%; border-collapse:collapse; margin-top:30px; border-top:2px solid #D4AF37; padding-top:20px;">
      <tr>
        <td style="padding:20px 0; font-family:Arial,sans-serif;">
          <p style="margin:0 0 4px 0; font-size:16px; font-weight:bold; color:#1a1a1a;">BookaRide Support Team</p>
          <p style="margin:0 0 4px 0; font-size:13px; color:#666;">Premium Airport Transfers &amp; Private Tours — Auckland, NZ</p>
          <p style="margin:0 0 4px 0; font-size:13px; color:#666;">
            <span style="color:#D4AF37; font-weight:bold;">P:</span> <a href="tel:+6421743321" style="color:#1a1a1a; text-decoration:none;">021 743 321</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <span style="color:#D4AF37; font-weight:bold;">E:</span> <a href="mailto:support@bookaride.co.nz" style="color:#1a1a1a; text-decoration:none;">support@bookaride.co.nz</a>
          </p>
          <p style="margin:0 0 4px 0; font-size:13px; color:#666;">
            <span style="color:#D4AF37; font-weight:bold;">W:</span> <a href="https://bookaride.co.nz" style="color:#1a1a1a; text-decoration:none;">bookaride.co.nz</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <span style="color:#D4AF37; font-weight:bold;">Book Now:</span> <a href="https://bookaride.co.nz/book-now" style="color:#D4AF37; text-decoration:none; font-weight:bold;">Get Instant Quote</a>
          </p>
          <p style="margin:12px 0 0 0; font-size:11px; color:#999; font-style:italic;">
            This reply was generated by our AI support assistant. For complex requests, our team will follow up within 24 hours.
          </p>
        </td>
      </tr>
    </table>
  `;
}

/**
 * Call Claude API to generate a contextual reply to the contact form message
 */
async function generateAutoReply(name, email, subject, message) {
  const apiKey = (process.env.ANTHROPIC_API_KEY || '').trim();
  if (!apiKey) return null;

  const systemPrompt = `You are the friendly, professional customer support assistant for BookaRide NZ — a premium airport transfer and private tour service in Auckland, New Zealand.

The customer has submitted a contact form on the website. Write a helpful, warm reply.

Key info:
- Online booking with instant live pricing at bookaride.co.nz/book-now
- Phone/text: 021 743 321
- Prices are per-km (every address is different) — direct them to bookaride.co.nz/book-now for exact quotes
- Minimum fare: $150 per one-way trip
- Service areas: Auckland CBD, North Shore, Hibiscus Coast, Rodney, wider Auckland
- Available 24/7 for airport transfers
- Payment: Credit/Debit Card, Cash, or Invoice

RULES:
- Keep it concise (under 150 words)
- Be warm and professional
- NEVER make up prices — always direct to the online quote tool
- Sign off as "BookaRide Support Team"`;

  const userMessage = `Contact form submission:\n\nName: ${name}\nEmail: ${email}\nSubject: ${subject || 'General Inquiry'}\n\nMessage:\n${message}\n\nPlease write a helpful reply.`;

  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 300,
        system: systemPrompt,
        messages: [{ role: 'user', content: userMessage }],
      }),
    });

    if (!res.ok) return null;
    const data = await res.json();
    return (data.content?.[0]?.text || '').trim();
  } catch (err) {
    console.error('Claude API error for contact auto-reply:', err.message);
    return null;
  }
}

module.exports = async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ detail: 'Method not allowed' });

  try {
    const { name, email, phone, message, subject } = req.body;

    if (!name || !email || !message) {
      return res.status(400).json({ detail: 'Name, email, and message are required' });
    }

    // Log the contact submission
    await insertOne('contact_submissions', {
      id: uuidv4(),
      name,
      email,
      phone: phone || '',
      message,
      subject: subject || 'General Inquiry',
      createdAt: new Date().toISOString(),
    }).catch(err => console.error('Failed to log contact submission:', err.message));

    // Send to admin
    const adminEmail = process.env.CONTACT_NOTIFICATION_EMAIL || process.env.BOOKINGS_NOTIFICATION_EMAIL || 'bookings@bookaride.co.nz';
    await sendEmail({
      to: adminEmail,
      subject: `Contact Form: ${subject || 'General Inquiry'} - ${name}`,
      html: `<h2>New Contact Form Submission</h2>
        <p><strong>Name:</strong> ${name}</p>
        <p><strong>Email:</strong> ${email}</p>
        <p><strong>Phone:</strong> ${phone || 'Not provided'}</p>
        <p><strong>Subject:</strong> ${subject || 'General Inquiry'}</p>
        <hr />
        <p>${message.replace(/\n/g, '<br />')}</p>`,
      replyTo: email,
    });

    // Send AI-powered auto-reply to the customer
    let replyText = await generateAutoReply(name, email, subject, message);
    if (!replyText) {
      replyText = `Hi ${name},\n\nThank you for contacting BookaRide. We've received your message and our team will get back to you within 24 hours.\n\nFor instant pricing, visit bookaride.co.nz/book-now or call/text 021 743 321.\n\nKind regards,\nBookaRide Support Team`;
    }

    const replyHtml = `
      <div style="font-family:Arial,sans-serif; max-width:600px; margin:0 auto; padding:20px; color:#333;">
        <div style="font-size:14px; line-height:1.7; color:#1a1a1a;">
          ${replyText.replace(/\n/g, '<br>')}
        </div>
        ${supportEmailSignature()}
      </div>
    `;

    await sendEmail({
      to: email,
      subject: `Re: ${subject || 'Your Message'} - BookaRide`,
      html: replyHtml,
      fromName: 'BookaRide Support',
      from: 'support@bookaride.co.nz',
      replyTo: 'support@bookaride.co.nz',
    }).catch(err => console.error('Failed to send auto-reply:', err.message));

    return res.status(200).json({ success: true, message: 'Message sent successfully' });
  } catch (err) {
    console.error('Contact form error:', err.message);
    return res.status(500).json({ detail: 'Failed to send message. Please try again.' });
  }
};
